### ISSUE TITLE
Multiple top-level packages discovered in a flat-layout

### ISSUE THREAD

**Issue by orientnab** [roboticslab-uc3m/gymnasium-playground#7]
On installation pip throws:

`error: Multiple top-level packages discovered in a flat-layout`

It seems it can be fixed by specifying the package in `setup.py`.

```
setup(
    ...,
    packages=["gymnasium_playground_gridworld"],
)
```

**Comment by jgvictores** [comment]
Hi!

I know the solution you propose is very easy to incorporate, but I'm curious given the context:

- `python setup.py check` only asks for `url` and `either (author and author_email) or (maintainer and maintainer_email)`
- https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packages says that although the packages can be listed manually, `setuptools.find_packages()` finds them automatically.
- No mention of the `packages` field in https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use (`setup.py` tab)
- I may be wrong on this one, but I do not see any "Multiple top-level packages" :sweat_smile:

Quite a bit of blame on `setuptools` found via <https://www.google.com/search?q=Multiple+top-level+packages+discovered+in+a+flat-layout>.

1. Which version are you using (`pip list | grep setuptools`)?
1. Could you try with a more recent version?

Cheers!

**Comment by orientnab** [comment]
It seems something has become stricter or more explicit since 61.0.
I'm on 65.5, I don't think a new version will change much.

_Please note that it is not possible to automatically derive a single name when the distribution consists of multiple top-level packages or modules._ (https://setuptools.pypa.io/en/latest/history.html#v61-0-0)

_Users that don’t set packages, py_modules, or configuration are still likely to observe the auto-discovery behavior, which may halt the build if the project contains multiple directories and/or multiple Python files directly under the project root._ (https://setuptools.pypa.io/en/latest/history.html#v61-1-0)
